name: Deploy the Nginx container 

on:
  push:    
    tags:     # Only run when a new tag is pushed to the repository
      - 'v*'  

  workflow_dispatch:

env:
  CONTAINER_NAME: nginx-container
  SERVICE_NAME: nginx  
  
jobs:  
  build_and_push:
    
    runs-on: ubuntu-latest
    
    steps:       
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
                      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:          
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
        
      - name: Get the version
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:          
          context: .
          file: ./Dockerfile
          registry: ${{ env.REGISTRY }}
          push: true          
          tags: nextmasjiddocker/nextmasjid-nginx:${{ steps.tag.outputs.VERSION }},  nextmasjiddocker/nextmasjid-nginx:latest  

      - name: Install SSH Key
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.SERVER }}  

      - name: Copy docker-compose
        run: scp docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER }}:/home/${{ secrets.SERVER_USER }}/
            
      - name: Deploy the new nginx image        
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: CONTAINER_NAME, SERVICE_NAME
          script: |            
            RESULT=$(docker container ps -q -f name=$CONTAINER_NAME)
            if [[ ! -z $RESULT ]]; then             
              docker-compose -f $HOME/docker-compose.yml rm -sf $SERVICE_NAME 
            fi
            docker system prune -af            
            docker-compose -f $HOME/docker-compose.yml up -d $SERVICE_NAME          
            rm -rf $HOME/docker-compose.yml     
